#!/bin/bash
## Get staged files list exceprt for deleted filed, and run trafflehod to scan secrets
git diff --cached --name-only --diff-filter=d | xargs -I {} trufflehog filesystem {} --no-update --fail